version: "3.8"
services:
  database: 
     environment:
      - MONGO_INITDB_ROOT_USERNAME=prod1812
      - MONGO_INITDB_ROOT_PASSWORD=prod123  
  javawebapp:  
     environment:
       - MONGO_DB_USERNAME=prod1812
       - MONGO_DB_PASSWORD=prod123
