version: "3.8"
services:
  database: 
     image: mongo
     restart: always  
     volumes:
        - chaituvol:/data/db
     networks:
       - openshift  
  javawebapp:
     image: chaitu1812/springbootmongo  
     environment:
       - MONGO_DB_HOSTNAME=database  
     restart: always    
     depends_on: 
       - database
     networks:
       - openshift
     ports:
       - 8084:8080

volumes:
  chaituvol: {}  
networks:
  openshift: {}  
